# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('location', models.CharField(max_length=264)),
            ],
        ),
    ]
