# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_resturant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resturant',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
    ]
